# Generated by Django 5.0.6 on 2024-07-01 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_chofer_transfer_disponible'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='idChofer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.chofer', verbose_name='Chofer'),
        ),
    ]
