# Generated by Django 5.0.6 on 2024-07-02 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_ticket_detalleticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='maxAsientos',
            field=models.PositiveIntegerField(default=99, verbose_name='Cantidad Máxima de Asientos'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='cantAsientos',
            field=models.PositiveIntegerField(verbose_name='Cantidad de Asientos Disponibles'),
        ),
    ]
