# Generated by Django 5.0.6 on 2024-07-02 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_transfer_maxasientos_alter_transfer_cantasientos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detalleticket',
            old_name='id',
            new_name='idDetalle',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='id',
            new_name='idTicket',
        ),
    ]
