# Generated by Django 5.0.6 on 2024-07-03 00:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_id_detalleticket_iddetalle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleticket',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_ticket', to='core.ticket'),
        ),
    ]
