# Generated by Django 5.0.6 on 2024-07-04 03:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_detalleticket_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='fechaReserva',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
